import type { Metadata } from "next";
import AuthProvider from "@/contex/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <AuthProvider>
          {/* <Navbar /> */}
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
